name: ghw_december
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  material: ^1.0.0+2
  english_words: ^4.0.0

flutter:
  # material: ^1.0.0+2
  uses-material-design: true
